#!/bin/bash

if [ "$#" -ne 2 ]; then
	echo "ERROR: Illegal number of parameters. Please enter exactly 2 parameters."
	echo "USAGE: lc file1 file2"
	echo "DESCRIPTION: lc will read from file1 and print all contents to file two as lower case."
	echo "OR: Run lcmain to convert uppercase text to lowercase text on the command line."
	exit
fi
	./lcmain < $1 > $2
